### PR TITLE
Shosh

### PR DESCRIPTION
**Pull request by shoshievass**
This is a bit jumbled but I wanted to rely on the roxygen package, so the package code in a folder "binscattr" which is *inside* the main 'binscattr' folder. Ick, I know - I'm a n00b, bear with me. 

Anyhow, from the external 'binscattr' folder, try running 'install("binscattr")' and then 

`
library(datasets)
data <- airquality %>% na.omit
binscatter(data, y="Ozone", x ="Temp", discrete=FALSE, controls=c("Solar.R", "Wind" ))
binscatter(data, y="Ozone", x ="Temp", discrete=FALSE)
`

without running any additional code. That should work. If you're happy with this framework, merge my branch with master; otherwise, let me know if you'd like to do :)

### CODE REVIEW

**Comment by paulgp** [comment]
Works for me. Need to update slightly the test case. I think the package needs to have a `require(tidyr)` command in it. 

`library(datasets) `
`library(tidyr)`
`library(binscattr)`
`data <- airquality %>% na.omit` 
`binscatter(data, y="Ozone", x ="Temp", discrete=FALSE, controls=c("Solar.R", "Wind" ))` `binscatter(data, y="Ozone", x ="Temp", discrete=FALSE)`

**Comment by shoshievass** [comment]
Ok so I didn't do a "require" but I added the package imports into the
roxygen namespace so that now dplyr, ggplot2, broom and felm from lfe are
installed whenever binscattr is installed. Ideally we'd install full
packages minimally and only take functions when we need them but this
should work in the meantime.

-Shosh

**Comment by paulgp** [comment]
Yeah, this is perfect.

**Comment by shoshievass** [comment]
:)

I was looking through Michael Stepner's package - I guess we should
implement all the fancy things he has?
https://michaelstepner.com/binscatter/binscatter-StataConference2014.pdf

In particular, the thing that seems sexiest to me would be to allow for
faceting by factors. I guess to do this we'd have to split the dataframe
into subsets by factor and do the residualizing separately for each one,
then combine back and plot?

-Shosh

**Comment by shoshievass** [comment]
Do you want to hold off on publicizing the github till we're farther along
or maybe tell twitter so if someone else is interested they could tag along?

-Shosh

**Comment by paulgp** [comment]
Yes, that sounds right. I think you can do that pretty efficiently using
Purrr right? http://purrr.tidyverse.org/

**Comment by shoshievass** [comment]
Yeah that sounds about right. Are you willing to take a stab?

-Shosh

**Comment by paulgp** [comment]
Yeah, I can't do it right now, unfortunately. I can probably give it a shot
on the plane on THursday.

PGP

**Comment by shoshievass** [comment]
Sounds good :)


-Shosh

**Comment by shoshievass** [comment]
Wound up feeling motivated to do it myself. Got it to work, though it could
use a look over. Let me know what you think/what should go on the todo - no
need to rush through, I was just feeling motivated today [it was a
procrastinaty day :p]

-Shosh

**Pull request merged**
