### PR TITLE
Added binscattr_by_group function + related things

### PR DESCRIPTION
**Pull request by shoshievass**
I decided to do make binscattr_by_group a separate function to keep the code cleaner. Let me know what you think..

A function call for testing is in test_binscattr_package.R

### CODE REVIEW

**Comment by paulgp** [comment]
Is there a reason why we're making such a strong R version requirement?

> install.packages("binscattr", repos = NULL, type="source")
> ERROR: this R is version 3.3.3, package 'binscattr' requires R >= 3.4.1

**Comment by shoshievass** [comment]
I don't think so - roxygen probably generated this automatically because
that's the R version I have installed on my machine..

-Shosh

**Comment by shoshievass** [comment]
I think if we change this line in the DESCRIPTION file, we can relax it:

'Depends: R (>= 3.4.1)'

-Shosh

**Comment by paulgp** [comment]
Can we edit it to allow earlier versions?

**Comment by shoshievass** [comment]
Yeah I think that's fine - we just need to choose some earlier version
that's compatible with all of our packages.

-Shosh

**Comment by shoshievass** [comment]
What are we using the broom package for, btw?

-Shosh

**Comment by paulgp** [comment]
I was using it to report the regression results (you put it as a wrapper
around felm)

**Comment by paulgp** [comment]
Ok, i will edit it in.

**Comment by shoshievass** [comment]
Awesome, thanks!

-Shosh

**Comment by paulgp** [comment]
So, I have this error when I try to run:

>  binscatter(data, y="Ozone", x ="Temp", discrete=FALSE, controls=c("Solar.R", "Wind" ))
> Error in mutate_impl(.data, dots) : 
>   Column `c()` is of unsupported type NULL
> > binscatter(data, y=Ozone, x =Tempb, discrete=FALSE)
> Error in mutate_impl(.data, dots) : 
>   Column `c()` is of unsupported type NULL

**Comment by shoshievass** [comment]
You're running from the latest push to my branch, yeah?

-Shosh

**Comment by shoshievass** [comment]
Looking into it

-Shosh

**Comment by paulgp** [comment]
Hrm, this might be a me-thing -- maybe my Git is messed up?

**Comment by shoshievass** [comment]
no, it was a bug! One sec, i'll push a fix

-Shosh

**Comment by shoshievass** [comment]
agh sorry, i got lost in the quo/enquo stuff. Finally fixed it!

-Shosh

**Comment by shoshievass** [comment]
Just pushed the fix

-Shosh

**Comment by paulgp** [comment]
Works perfectly!

**Pull request merged**
